#!/bin/bash

echo "Уважаемый пользователь!\n"
echo "Добро пожаловать во Всероссийскую"
echo "информационную систему единого"
echo "лингвопроектирования и центральной автоматизации"
echo "(ВИСЕЛИЦА). Это — последний доступный канал связи"
echo "после суверенизации российского интернета.\n"
echo "В базе данных ВИСЕЛИЦА содержится 2 976 464 738 "
echo "аббревиатур, необходимых для выполнения "
echo "протоколов взаимодействия. Для успешного "
echo "завершения Вашего обучения в системе Вам "
echo "необходимо пройти тест.\n"
echo "Перед Вашими глазами появится набор "
echo "букв. Из них Вам необходимо будет собрать "
echo "аббревиатуру по ее описанию."
echo "За каждую неудачную попытку у "
echo "вас будут отнимать один из десяти баллов. От "
echo "полученного результата зависит, в какое ведомство и "
echo "на какую должность Вы попадете по распределению.\n"
echo "Удачи, товарищ."
echo "------------------------------------------------------\n\n\n"

life=10
a1=0
a2=0
a3=0
a4=0
a5=0
a6=0
a7=0
a8=0
a9=0
a10=0
for ((a = 1; a <= 10; a++))
do
	if [ "$a" -eq "1" ] 
	then
		echo "Уровень 1/10"
		echo "Просто полиция"
		echo "Доступные буквы"
		echo "В Д М"
		echo "_ _ _"
		while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "МВД" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "\"МВД - Министерство внутренних дел\"\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
	elif [ $a -eq "2" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 2/10"
			echo "\"Журналисты постоянно путают это с СИЗО\""
			echo "Доступные буквы"
			echo "В И С"
			echo "_ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "ИВС" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "ИВС — Изолятор временного содержания\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
	elif [ $a -eq "3" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 3/10"
			echo "\"Тюремщики\""
			echo "Доступные буквы"
			echo "Н И С Ф"
			echo "_ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "ФСИН" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "ФСИН — Федеральная служба исполнения наказаний\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
		elif [ $a -eq "4" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 4/10"
			echo "\"Полицейский документ с записями обо всех происшествиях\""
			echo "Доступные буквы"
			echo "П У К C"
			echo "_ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "КУСП" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "КУСП — Книга учета сообщений о происшествиях (преступлениях)\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
		elif [ $a -eq "5" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 5/10"
			echo "\"Канцелярское управление МВД\""
			echo "Доступные буквы"
			echo "И Р Д У"
			echo "_ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "УДИР" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "УДИР — Управление делопроизводства и режима\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
		elif [ $a -eq "6" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 6/10"
			echo "\"Выдает лицензию на оружие\""
			echo "Доступные буквы"
			echo "Р О Л Р"
			echo "_ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "ОЛРР" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "ОЛРР — Отдел лицензионно-разрешительной работы\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
		elif [ $a -eq "7" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 7/10"
			echo "\"Любители махать дубинками на митингах\""
			echo "Доступные буквы"
			echo "Н О М О"
			echo "_ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "ОМОН" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "ОМОН — Отряд мобильный особого назначения\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
		elif [ $a -eq "8" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 8/10"
			echo "\"Отдел МВД, следящий за веществами\""
			echo "Доступные буквы"
			echo "О Н Б О Н"
			echo "_ _ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "ОБНОН" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "ОБНОН — Отдел по борьбе с незаконным оборотом наркотиков\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
		elif [ $a -eq "9" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 9/10"
			echo "\"«Убойный» отдел официальным языком\""
			echo "Доступные буквы"
			echo "Л П Р О П"
			echo "_ _ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "ОРППЛ" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "ОРППЛ — Отдел расследования преступлений против личности\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
		elif [ $a -eq "10" ]
	then
		if [ $life -ge 0 ]
		then
			echo "Уровень 10/10"
			echo "\"Документ, в котором сказано, сколько суток вы получите за митинг\""
			echo "Доступные буквы"
			echo "О А П К"
			echo "_ _ _ _"
					while [ $life -gt 0 ]
		do
			read name
			if [ "$name" = "КОАП" ]
			then
				break
			fi
			life=$(($life - 1))
		done
		if [ $life -gt 0 ]
		then
			echo "\nВерно!"
			echo "КОАП — Кодекс об административных правонарушениях\n"
			echo "---------------------------------------\n"
			read lol
		else
			break
		fi
		fi
	fi
done

if [ $a -le 3 ]
then
	echo "Мною разгаданы $(($a - 1)) из 10 "
	echo "аббревиатур\n"
	echo "Я — сотрудник Вневедомственного отдела техконтроля "
	echo "операторов сотовой связи (ВОТОПСОС)\n"
	echo "С такими знаниями аббревиатур карьеру в органах не "
	echo "построишь. Обещаю выучить УК и КоАП, перечитать "
	echo "все ДСП-инструкции и научиться отличать СБУ от УСБ."
elif [ $a -le 10 ]
then
	echo "Мною разгаданы $(($a - 1)) из 10 "
	echo "аббревиатур\n"
	echo "Я — старший научный сотрудник НИИЧЕГО, Научно-"
	echo "исследовательского института чрезвычайного "
	echo "епархиального государственного отдела.\n"
	echo "ОМОН, ШИЗО, ЕПКТ — все это минует меня, ведь моя "
	echo "карьера Божией милостью сложилась весьма успешно."
elif [ $a -eq 11 ]
then
	echo "Мною разгаданы $(($a - 1)) из 10 "
	echo "аббревиатур\n"
	echo "Я — создатель системы ВИСЕЛИЦА"
	echo "ОИСНВГВТВЦУТВЦПГНЖВГДКИАВБ! ЛБГОВВП "
	echo "ООУБЦЕРСВДИПБИОР? " 
	echo "УВСМГБУОРДЧВБКППИОРТВСЧ!"
fi